/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorDirectorio;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul Idrovo
 */
public class VistaDirectorio extends javax.swing.JFrame {

    private ControladorDirectorio controladorDirectorio;

    public VistaDirectorio() {
        initComponents();
        controladorDirectorio = new ControladorDirectorio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstDirectorio = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaInformacion = new javax.swing.JTextArea();
        btArchivosOcultos = new javax.swing.JButton();
        btDirectorioOculto = new javax.swing.JButton();
        txtRuta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btArchivos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnCrear = new javax.swing.JMenuItem();
        mnEliminar = new javax.swing.JMenuItem();
        mnRenombrar = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstDirectorio.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstDirectorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDirectorioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstDirectorio);

        txtaInformacion.setEditable(false);
        txtaInformacion.setColumns(20);
        txtaInformacion.setRows(5);
        jScrollPane2.setViewportView(txtaInformacion);

        btArchivosOcultos.setText("Listar Archivos Ocultos");
        btArchivosOcultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArchivosOcultosActionPerformed(evt);
            }
        });

        btDirectorioOculto.setText("Listar Directorios Ocultos");
        btDirectorioOculto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDirectorioOcultoActionPerformed(evt);
            }
        });

        txtRuta.setText("C:\\");
            txtRuta.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusLost(java.awt.event.FocusEvent evt) {
                    txtRutaFocusLost(evt);
                }
            });

            jLabel1.setText("RUTA:");

            btArchivos.setText("Listar Archivos ");
            btArchivos.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btArchivosActionPerformed(evt);
                }
            });

            jMenu1.setText("GESTIONAR DIRECTORIO");

            mnCrear.setText("Crear");
            mnCrear.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnCrearActionPerformed(evt);
                }
            });
            jMenu1.add(mnCrear);

            mnEliminar.setText("Eliminar");
            mnEliminar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnEliminarActionPerformed(evt);
                }
            });
            jMenu1.add(mnEliminar);

            mnRenombrar.setText("Renombrar");
            mnRenombrar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnRenombrarActionPerformed(evt);
                }
            });
            jMenu1.add(mnRenombrar);

            mnSalir.setText("Salir");
            mnSalir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnSalirActionPerformed(evt);
                }
            });
            jMenu1.add(mnSalir);

            jMenuBar1.add(jMenu1);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(jLabel1))
                                .addComponent(btArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(224, 244, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btArchivosOcultos)
                                    .addGap(36, 36, 36)
                                    .addComponent(btDirectorioOculto)
                                    .addGap(118, 118, 118))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(77, 77, 77))))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btArchivosOcultos)
                                .addComponent(btDirectorioOculto)
                                .addComponent(btArchivos))
                            .addGap(31, 31, 31)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(81, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void txtRutaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRutaFocusLost
        Listar();
    }//GEN-LAST:event_txtRutaFocusLost
    public void Listar() {
        controladorDirectorio.setRuta(txtRuta.getText());
        List<String> directorio = controladorDirectorio.listarDirectorio();
        if (directorio != null) {
            String imp[] = new String[directorio.size()];
            for (int i = 0; i < imp.length; i++) {
                imp[i] = directorio.get(i);
            }
            lstDirectorio.setListData(imp);
        } else {
            txtRuta.setText("C:\\");
        }
    }
    private void btDirectorioOcultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDirectorioOcultoActionPerformed
        controladorDirectorio.setRuta(txtRuta.getText());
        List<String> directorio = controladorDirectorio.listarDirectoriosOcultos();
        if (!directorio.isEmpty()) {
            String imp[] = new String[directorio.size()];
            for (int i = 0; i < imp.length; i++) {
                imp[i] = directorio.get(i);
            }
            lstDirectorio.setListData(imp);
        }
    }//GEN-LAST:event_btDirectorioOcultoActionPerformed

    private void btArchivosOcultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArchivosOcultosActionPerformed
        controladorDirectorio.setRuta(txtRuta.getText());
        List<String> directorio = controladorDirectorio.listarArchivosOcultos();
        if (!directorio.isEmpty()) {
            String imp[] = new String[directorio.size()];
            for (int i = 0; i < imp.length; i++) {
                imp[i] = directorio.get(i);
            }
            lstDirectorio.setListData(imp);
        }
    }//GEN-LAST:event_btArchivosOcultosActionPerformed

    private void btArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArchivosActionPerformed
        controladorDirectorio.setRuta(txtRuta.getText());
        List<String> directorio = controladorDirectorio.listarArchivos();
        if (!directorio.isEmpty()) {
            String imp[] = new String[directorio.size()];
            for (int i = 0; i < imp.length; i++) {
                imp[i] = directorio.get(i);
            }
            lstDirectorio.setListData(imp);
        }
    }//GEN-LAST:event_btArchivosActionPerformed

    private void lstDirectorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDirectorioMouseClicked
        if (!lstDirectorio.isSelectionEmpty()) {
            controladorDirectorio.setRuta(txtRuta.getText() + "\\" + lstDirectorio.getSelectedValue().toString());
            String datos = controladorDirectorio.mostrarInformacion();
            txtaInformacion.setText(datos);
        }
    }//GEN-LAST:event_lstDirectorioMouseClicked

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCrearActionPerformed
        String nombreDir = JOptionPane.showInputDialog("INGRESE EL NOMBRE DEL NUEVO DIRECTORIO", "");
        if (nombreDir.contains(".")) {
            controladorDirectorio.crearArchivo(txtRuta.getText() + "\\" + nombreDir);
        } else {
            controladorDirectorio.crearDirectorio(txtRuta.getText() + "\\" + nombreDir);
        }
        Listar();
    }//GEN-LAST:event_mnCrearActionPerformed

    private void mnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEliminarActionPerformed
        if (!lstDirectorio.isSelectionEmpty()) {
            int confirmar = JOptionPane.showConfirmDialog(null,
                    "<html>DESEA ELIMINAR EL REGISTRO <strong>" + lstDirectorio.getSelectedValue() + "</strong> ?</html>");

            if (JOptionPane.OK_OPTION == confirmar) {
                controladorDirectorio.eliminarDirectorio(new File(txtRuta.getText() + "\\" + lstDirectorio.getSelectedValue().toString()));
                JOptionPane.showMessageDialog(null, "EL DIRECTORIO " + lstDirectorio.getSelectedValue() + " HA SIDO ELIMINADO", "ELIMINAR", JOptionPane.INFORMATION_MESSAGE);
                Listar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "NO SE HA SELECCIONADO NINGUN DIRECTORIO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnEliminarActionPerformed

    private void mnRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRenombrarActionPerformed
        if (!lstDirectorio.isSelectionEmpty()) {
            int confirmar = JOptionPane.showConfirmDialog(null,
                    "<html>DESEA EDITAR EL REGISTRO <strong>" + lstDirectorio.getSelectedValue() + "</strong> ?</html>");

            if (JOptionPane.OK_OPTION == confirmar) {
                String nombreDir = JOptionPane.showInputDialog("INGRESE EL NUEVO NOMBRE DEL NUEVO DIRECTORIO", "");
                controladorDirectorio.renombrarDirectorio(txtRuta.getText() + "\\" + lstDirectorio.getSelectedValue().toString(), txtRuta.getText() + "\\" + nombreDir);
                JOptionPane.showMessageDialog(null, "EL DIRECTORIO HA SIDO RENOMBRADO ", "RENOMBRADO", JOptionPane.INFORMATION_MESSAGE);
                Listar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "NO SE HA SELECCIONADO NINGUN DIRECTORIO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnRenombrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaDirectorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btArchivos;
    private javax.swing.JButton btArchivosOcultos;
    private javax.swing.JButton btDirectorioOculto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstDirectorio;
    private javax.swing.JMenuItem mnCrear;
    private javax.swing.JMenuItem mnEliminar;
    private javax.swing.JMenuItem mnRenombrar;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JTextArea txtaInformacion;
    // End of variables declaration//GEN-END:variables
}
