/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorDirectorio;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.crypto.AEADBadTagException;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Paul Idrovo
 */
public class VistaDirectorio extends javax.swing.JFrame {

    private ControladorDirectorio controladorDirectorio;
    private String rutaAntigua;

    public VistaDirectorio() {
        initComponents();
        controladorDirectorio = new ControladorDirectorio();
        rutaAntigua = "";
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/carpeta.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstDirectorio = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaInformacion = new javax.swing.JTextArea();
        btArchivosOcultos = new javax.swing.JButton();
        btDirectorioOculto = new javax.swing.JButton();
        txtRuta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btArchivos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnCrear = new javax.swing.JMenuItem();
        mnEliminar = new javax.swing.JMenuItem();
        mnRenombrar = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DIRECTORIO");

        lstDirectorio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lstDirectorio.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstDirectorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDirectorioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstDirectorio);

        txtaInformacion.setEditable(false);
        txtaInformacion.setColumns(20);
        txtaInformacion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtaInformacion.setRows(5);
        jScrollPane2.setViewportView(txtaInformacion);

        btArchivosOcultos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btArchivosOcultos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/estadistica.png"))); // NOI18N
        btArchivosOcultos.setText("Listar Archivos Ocultos");
        btArchivosOcultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArchivosOcultosActionPerformed(evt);
            }
        });

        btDirectorioOculto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btDirectorioOculto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/carpeta.png"))); // NOI18N
        btDirectorioOculto.setText("Listar Directorios Ocultos");
        btDirectorioOculto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDirectorioOcultoActionPerformed(evt);
            }
        });

        txtRuta.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtRuta.setText("C:\\");
            txtRuta.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    txtRutaFocusGained(evt);
                }
                public void focusLost(java.awt.event.FocusEvent evt) {
                    txtRutaFocusLost(evt);
                }
            });

            jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
            jLabel1.setText("RUTA:");

            btArchivos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            btArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/estadistica.png"))); // NOI18N
            btArchivos.setText("Listar Archivos ");
            btArchivos.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btArchivosActionPerformed(evt);
                }
            });

            jMenuBar1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

            jMenu1.setText("GESTIONAR DIRECTORIO");

            mnCrear.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            mnCrear.setText("Crear");
            mnCrear.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnCrearActionPerformed(evt);
                }
            });
            jMenu1.add(mnCrear);

            mnEliminar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            mnEliminar.setText("Eliminar");
            mnEliminar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnEliminarActionPerformed(evt);
                }
            });
            jMenu1.add(mnEliminar);

            mnRenombrar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            mnRenombrar.setText("Renombrar");
            mnRenombrar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnRenombrarActionPerformed(evt);
                }
            });
            jMenu1.add(mnRenombrar);

            mnSalir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            mnSalir.setText("Salir");
            mnSalir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnSalirActionPerformed(evt);
                }
            });
            jMenu1.add(mnSalir);

            jMenuBar1.add(jMenu1);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtRuta))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(99, 99, 99)
                            .addComponent(btArchivosOcultos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(80, 80, 80)
                            .addComponent(btDirectorioOculto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGap(38, 38, 38))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btArchivos)
                                .addComponent(btDirectorioOculto)
                                .addComponent(btArchivosOcultos)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(20, 20, 20))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void txtRutaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRutaFocusLost
        Listar();
    }//GEN-LAST:event_txtRutaFocusLost
    public void Listar() {
        controladorDirectorio.setRuta(txtRuta.getText());
        List<String> directorio = controladorDirectorio.listarDirectorio();
        if (directorio != null) {
            String imp[] = new String[directorio.size()];
            for (int i = 0; i < imp.length; i++) {
                imp[i] = directorio.get(i);
            }
            lstDirectorio.setListData(imp);
            rutaAntigua = txtRuta.getText();
        } else {
            JOptionPane.showMessageDialog(null, "<html>El DIRECTORIO <strong>" + txtRuta.getText() + "</strong> NO EXISTE", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtRuta.setText(rutaAntigua);
        }
    }
    private void btDirectorioOcultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDirectorioOcultoActionPerformed
        controladorDirectorio.setRuta(txtRuta.getText());
        List<String> directorio = controladorDirectorio.listarDirectoriosOcultos();
        if (!directorio.isEmpty()) {
            String imp[] = new String[directorio.size()];
            DefaultListModel<String> model = new DefaultListModel<>();
            for (int i = 0; i < imp.length; i++) {
                model.addElement(directorio.get(i));
                //imp[i] = directorio.get(i);
            }
            //lstDirectorio.setListData(imp);
            lstDirectorio.setModel(model);
        }
    }//GEN-LAST:event_btDirectorioOcultoActionPerformed

    private void btArchivosOcultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArchivosOcultosActionPerformed
        controladorDirectorio.setRuta(txtRuta.getText());
        List<String> directorio = controladorDirectorio.listarArchivosOcultos();
        if (!directorio.isEmpty()) {
            String imp[] = new String[directorio.size()];
            for (int i = 0; i < imp.length; i++) {
                imp[i] = directorio.get(i);
            }
            lstDirectorio.setListData(imp);
        }
    }//GEN-LAST:event_btArchivosOcultosActionPerformed

    private void btArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArchivosActionPerformed
        controladorDirectorio.setRuta(txtRuta.getText());
        List<String> directorio = controladorDirectorio.listarArchivos();
        if (!directorio.isEmpty()) {
            String imp[] = new String[directorio.size()];
            for (int i = 0; i < imp.length; i++) {
                imp[i] = directorio.get(i);
            }
            lstDirectorio.setListData(imp);
        }
    }//GEN-LAST:event_btArchivosActionPerformed

    private void lstDirectorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDirectorioMouseClicked
        if (!lstDirectorio.isSelectionEmpty()) {
            txtRuta.setText(rutaAntigua);
            txtRuta.setText(txtRuta.getText() + "\\" + lstDirectorio.getSelectedValue().toString());
            controladorDirectorio.setRuta(txtRuta.getText());
            String datos = controladorDirectorio.mostrarInformacion();
            txtaInformacion.setText(datos);
        }
    }//GEN-LAST:event_lstDirectorioMouseClicked

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCrearActionPerformed
        String nombreDir = JOptionPane.showInputDialog("INGRESE EL NOMBRE DEL NUEVO DIRECTORIO", "");
        if (nombreDir.contains(".")) {
            controladorDirectorio.crearArchivo(txtRuta.getText() + "\\" + nombreDir);
        } else {
            controladorDirectorio.crearDirectorio(txtRuta.getText() + "\\" + nombreDir);
        }
        Listar();
    }//GEN-LAST:event_mnCrearActionPerformed

    private void mnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEliminarActionPerformed
        if (!lstDirectorio.isSelectionEmpty()) {
            int confirmar = JOptionPane.showConfirmDialog(null,
                    "<html>DESEA ELIMINAR EL REGISTRO <strong>" + lstDirectorio.getSelectedValue() + "</strong> ?</html>");

            if (JOptionPane.OK_OPTION == confirmar) {
                controladorDirectorio.eliminarDirectorio(new File(txtRuta.getText() + "\\" + lstDirectorio.getSelectedValue().toString()));
                JOptionPane.showMessageDialog(null, "EL DIRECTORIO " + lstDirectorio.getSelectedValue() + " HA SIDO ELIMINADO", "ELIMINAR", JOptionPane.INFORMATION_MESSAGE);
                Listar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "NO SE HA SELECCIONADO NINGUN DIRECTORIO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnEliminarActionPerformed

    private void mnRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRenombrarActionPerformed
        if (!lstDirectorio.isSelectionEmpty()) {
            int confirmar = JOptionPane.showConfirmDialog(null,
                    "<html>DESEA EDITAR EL REGISTRO <strong>" + lstDirectorio.getSelectedValue() + "</strong> ?</html>");

            if (JOptionPane.OK_OPTION == confirmar) {
                String nombreDir = JOptionPane.showInputDialog("INGRESE EL NUEVO NOMBRE DEL NUEVO DIRECTORIO", "");
                controladorDirectorio.renombrarDirectorio(txtRuta.getText() + "\\" + lstDirectorio.getSelectedValue().toString(), txtRuta.getText() + "\\" + nombreDir);
                JOptionPane.showMessageDialog(null, "EL DIRECTORIO HA SIDO RENOMBRADO ", "RENOMBRADO", JOptionPane.INFORMATION_MESSAGE);
                Listar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "NO SE HA SELECCIONADO NINGUN DIRECTORIO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnRenombrarActionPerformed

    private void txtRutaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRutaFocusGained
        rutaAntigua = txtRuta.getText();
    }//GEN-LAST:event_txtRutaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                    System.out.println("Error setting Java LAF: " + e);
                }
                new VistaDirectorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btArchivos;
    private javax.swing.JButton btArchivosOcultos;
    private javax.swing.JButton btDirectorioOculto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstDirectorio;
    private javax.swing.JMenuItem mnCrear;
    private javax.swing.JMenuItem mnEliminar;
    private javax.swing.JMenuItem mnRenombrar;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JTextArea txtaInformacion;
    // End of variables declaration//GEN-END:variables
}
